services:
  - type: web
    name: alaa-academy
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python setup_production.py
    startCommand: gunicorn alaa_academy.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: alaa-academy-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SETTINGS_MODULE
        value: alaa_academy.settings

  - type: pserv
    name: alaa-academy-db
    env: postgresql
    plan: free
    databaseName: alaa_academy
    databaseUser: alaa_academy_user
