# Generated by Django 5.2.1 on 2025-07-12 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='مستخدمون جدد')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='مستخدمون نشطون')),
                ('new_enrollments', models.PositiveIntegerField(default=0, verbose_name='تسجيلات جديدة')),
                ('completed_courses', models.PositiveIntegerField(default=0, verbose_name='دورات مكتملة')),
                ('certificates_issued', models.PositiveIntegerField(default=0, verbose_name='شهادات صادرة')),
                ('total_learning_time', models.PositiveIntegerField(default=0, help_text='إجمالي وقت التعلم بالدقائق', verbose_name='إجمالي وقت التعلم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إحصائيات يومية',
                'verbose_name_plural': 'الإحصائيات اليومية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.PositiveIntegerField(default=0, verbose_name='إجمالي التسجيلات')),
                ('active_enrollments', models.PositiveIntegerField(default=0, verbose_name='التسجيلات النشطة')),
                ('completed_enrollments', models.PositiveIntegerField(default=0, verbose_name='التسجيلات المكتملة')),
                ('average_completion_time', models.FloatField(default=0.0, help_text='متوسط وقت الإكمال بالأيام', verbose_name='متوسط وقت الإكمال')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='متوسط التقييم')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='إجمالي التقييمات')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='إجمالي المشاهدات')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'تحليلات الدورة',
                'verbose_name_plural': 'تحليلات الدورات',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('course_view', 'عرض دورة'), ('content_view', 'عرض محتوى'), ('content_complete', 'إكمال محتوى'), ('course_enroll', 'تسجيل في دورة'), ('course_complete', 'إكمال دورة'), ('certificate_download', 'تحميل شهادة'), ('profile_update', 'تحديث الملف الشخصي')], max_length=20, verbose_name='الإجراء')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط المستخدم',
                'verbose_name_plural': 'أنشطة المستخدمين',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_779c80_idx'), models.Index(fields=['action', '-timestamp'], name='analytics_u_action_d695f0_idx')],
            },
        ),
    ]
