# Generated by Django 5.2.1 on 2025-07-12 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, help_text='اسم أيقونة Bootstrap أو Font Awesome', max_length=50, null=True, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#007bff', help_text='لون الفئة بصيغة hex', max_length=7, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('short_description', models.CharField(max_length=300, verbose_name='وصف مختصر')),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/', verbose_name='صورة الدورة')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='مستوى الصعوبة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر')),
                ('estimated_duration', models.PositiveIntegerField(help_text='المدة المقدرة بالساعات', verbose_name='المدة المقدرة')),
                ('prerequisites', models.TextField(blank=True, null=True, verbose_name='المتطلبات المسبقة')),
                ('learning_objectives', models.TextField(verbose_name='أهداف التعلم')),
                ('is_featured', models.BooleanField(default=False, verbose_name='دورة مميزة')),
                ('enrollment_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد التسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category', verbose_name='الفئة')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='المدرب')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المحتوى')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('content_type', models.CharField(choices=[('video', 'فيديو'), ('pdf', 'ملف PDF'), ('quiz', 'اختبار'), ('assignment', 'مهمة')], max_length=20, verbose_name='نوع المحتوى')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='رابط الملف')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='course_content/', verbose_name='رفع الملف')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='المدة بالدقائق', null=True, verbose_name='المدة')),
                ('order_sequence', models.PositiveIntegerField(default=1, verbose_name='ترتيب التسلسل')),
                ('is_free', models.BooleanField(default=False, verbose_name='مجاني')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='courses.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'محتوى الدورة',
                'verbose_name_plural': 'محتويات الدورة',
                'ordering': ['course', 'order_sequence'],
                'unique_together': {('course', 'order_sequence')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='نسبة التقدم')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='آخر وصول')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='الدورة')),
                ('registration_code_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.registrationcode', verbose_name='كود التسجيل المستخدم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('certificate_url', models.URLField(blank=True, null=True, verbose_name='رابط الشهادة')),
                ('is_verified', models.BooleanField(default=True, verbose_name='تم التحقق')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='الدرجة')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='courses.enrollment', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='الوقت المقضي بالثواني', verbose_name='الوقت المقضي')),
                ('last_position', models.PositiveIntegerField(default=0, help_text='آخر موضع في الفيديو بالثواني', verbose_name='آخر موضع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.coursecontent', verbose_name='المحتوى')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.enrollment', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'تقدم الطالب',
                'verbose_name_plural': 'تقدم الطلاب',
                'ordering': ['content__order_sequence'],
                'unique_together': {('enrollment', 'content')},
            },
        ),
    ]
